language: node_js

cache:
  yarn: true

stages:
  - lint
  - test

jobs:
  include:

    - stage: lint
      script:
        - yarn run lint

    - stage: test
      script:
        - yarn test
      branches:
        except:
          - master

    - stage: test
      script:
        - yarn run test-coverage
      branches:
        only:
          - master
